Rule8897
data-to-insight/CIN-validator pull request #173
Opened 2022-11-03 15:00 UTC by WendyWigan

Closes #63

2022-11-07 09:19 UTC, willLPD2I requested changes

2022-11-07 09:19 UTC, willLPD2I commented on cin_validator/rules/cin2022_23/rule_8897.py
> +    condition2 = df[AssessmentFactors].isna()
Hi Wendy, this rule needs you to check both if AssessmentFactor is present AND if it's a valid code. The codes can be found here: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1025195/Children_in_need_census_2022_to_2023_guide.pdf

To test if particular column on a particular row contains a valid code, I'd first make a list of valid codes, then use the .isin(codes_list_name) method on the column of the df, just as you have used .isna() and .notna() for conditions 1 and 2. If you feel you don't have time to do this, I'm happy to do it and send you an email with pictures explaining what I've done.

2022-11-07 09:19 UTC, willLPD2I commented on cin_validator/rules/cin2022_23/rule_8897.py
> +                "LAchildID": "child1",
As you need to check fro valid codes, you'll need to add some passing and failing codes here too!

2022-11-07 09:19 UTC, willLPD2I commented on cin_validator/rules/cin2022_23/rule_8897.py
> +                    "child3",
This'll also need to account for the codes

2022-11-08 15:35 UTC, WendyWigan commented
Hi Will

I don’t think that I will be able to do this as plans have changed for this week. I’m happy for you to complete and send me screen shots of how it has been updated/completed.

Regards


Wendy Yates
Research & Information Officer
Joint Intelligence Unit (Mon-Thurs only)
Resources Directorate
Wigan Council
Wigan New Town Hall, Library Street, Wigan WN1 1YN
01942 489996 (89996) CURRENTLY NOT IN USE
www.wigan.gov.uk
www.twitter.com/wigancouncil
www.facebook.com/WiganCouncilOnline




From: willLPD2I ***@***.***>
Sent: 07 November 2022 09:20
To: data-to-insight/CIN-validator ***@***.***>
Cc: Yates, Wendy ***@***.***>; Author ***@***.***>
Subject: Re: [data-to-insight/CIN-validator] Rule8897 (PR #173)

CAUTION External E-Mail: Take extra care before clicking links, attachments and actioning requests. Think Before you Click



@willLPD2I requested changes on this pull request.

________________________________

In cin_validator/rules/cin2022_23/rule_8897.py<https://clicktime.symantec.com/15t5ehGT3hZUREjD3dNgR?h=v_g-dQG7oCc3-vEzu4RN3hph9932MaAcE9Lb41cnUN0=&u=https://github.com/data-to-insight/CIN-validator/pull/173%23discussion_r1015176874>:

> +    # Before you begin, rename the index so that the initial row positions can be kept intact.

+    df.index.name = "ROW_ID"

+

+    # lOGIC

+    # Implement rule logic as described by the Github issue.

+    # Put the description as a comment above the implementation as shown.

+

+    # Where present, if <AssessmentAuthorisationDate> (N00160) is on or after [Start_Of_Census_Year] then one or more <AssessmentFactors> (N00181) must be present within the same assessment module and must be a valid code

+    # Get collection period

+    header = data_container[Header]

+    ref_date_series = header[ReferenceDate]

+    collection_start, collection_end = make_census_period(ref_date_series)

+    condition1 = (df[AssessmentAuthorisationDate] >= collection_start) & (

+        df[AssessmentAuthorisationDate].notna()

+    )

+    condition2 = df[AssessmentFactors].isna()

Hi Wendy, this rule needs you to check both if AssessmentFactor is present AND if it's a valid code. The codes can be found here: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1025195/Children_in_need_census_2022_to_2023_guide.pdf<https://clicktime.symantec.com/15t5Zs5Ab5st1HuHW4yXo?h=ACm0THubD-gADaF0SEf1mQqZRYrSIudb1PvrSlkQujM=&u=https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1025195/Children_in_need_census_2022_to_2023_guide.pdf>

To test if particular column on a particular row contains a valid code, I'd first make a list of valid codes, then use the .isin(codes_list_name) method on the column of the df, just as you have used .isna() and .notna() for conditions 1 and 2. If you feel you don't have time to do this, I'm happy to do it and send you an email with pictures explaining what I've done.

________________________________

In cin_validator/rules/cin2022_23/rule_8897.py<https://clicktime.symantec.com/15t5jXTjWKF4qBZ8bBmq3?h=oJAcSXJWdQngHY_JHLZ6ESPnTUfVqUGaMPoawjuXWTA=&u=https://github.com/data-to-insight/CIN-validator/pull/173%23discussion_r1015177605>:

> +    df_issues["ERROR_ID"] = link_id

+    df_issues = df_issues.groupby("ERROR_ID")["ROW_ID"].apply(list).reset_index()

+    # Ensure that you do not change the ROW_ID, and ERROR_ID column names which are shown above. They are keywords in this project.

+    rule_context.push_type_1(

+        table=Assessments,

+        columns=[AssessmentAuthorisationDate, AssessmentFactors],

+        row_df=df_issues,

+    )

+

+

+def test_validate():

+    # Create some sample data such that some values pass the validation and some fail.

+    fake_data = pd.DataFrame(

+        [

+            {

+                "LAchildID": "child1",

As you need to check fro valid codes, you'll need to add some passing and failing codes here too!

________________________________

In cin_validator/rules/cin2022_23/rule_8897.py<https://clicktime.symantec.com/15t5pMf1xvvfF8P48kAyf?h=IU5pn1h1qDlsQkx5t4sskAYKJUADQpiJJfdgnM9oYZk=&u=https://github.com/data-to-insight/CIN-validator/pull/173%23discussion_r1015177861>:

> +    # replace 2 with the number of failing points you expect from the sample data.

+    assert len(issue_rows) == 1

+    # check that the failing locations are contained in a DataFrame having the appropriate columns. These lines do not change.

+    assert isinstance(issue_rows, pd.DataFrame)

+    assert issue_rows.columns.to_list() == ["ERROR_ID", "ROW_ID"]

+

+    # Create the dataframe which you expect, based on the fake data you created. It should have two columns.

+    # - The first column is ERROR_ID which contains the unique combination that identifies each error instance, which you decided on earlier.

+    # - The second column in ROW_ID which contains a list of index positions that belong to each error instance.

+

+    # The ROW ID values represent the index positions where you expect the sample data to fail the validation check.

+    expected_df = pd.DataFrame(

+        [

+            {

+                "ERROR_ID": (

+                    "child3",

This'll also need to account for the codes

—
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/15t5uBrJRYcFf5CygJa8H?h=uCEGKl8l-7v8uzTemm3KeDdRpbenYfzB8fgbIblci4A=&u=https://github.com/data-to-insight/CIN-validator/pull/173%23pullrequestreview-1170042517>, or unsubscribe<https://clicktime.symantec.com/15t5z23atAHr522uDryGu?h=t17mMUfT4dgcpPiMhW-osTZe07r31nkz_Igd3HaCmOk=&u=https://github.com/notifications/unsubscribe-auth/A3CF6DSGERTTJ6SEHB3QJULWHDCS5ANCNFSM6AAAAAARWHOE64>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________
>><<
[https://www.wigan.gov.uk/pub/emailsignature/footer.png]

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

2022-11-08 15:37 UTC, willLPD2I commented
Great Wendy, I’ll do it!

William Levack-Payne (He/Him)
Data Advocate (Data to Insight)
Children’s Services

07732 824391 | ***@***.******@***.***>

From: WendyWigan ***@***.***>
Sent: 08 November 2022 15:35
To: data-to-insight/CIN-validator ***@***.***>
Cc: William Levack-Payne ***@***.***>; Mention ***@***.***>
Subject: Re: [data-to-insight/CIN-validator] Rule8897 (PR #173)

Hi Will

I don’t think that I will be able to do this as plans have changed for this week. I’m happy for you to complete and send me screen shots of how it has been updated/completed.

Regards


Wendy Yates
Research & Information Officer
Joint Intelligence Unit (Mon-Thurs only)
Resources Directorate
Wigan Council
Wigan New Town Hall, Library Street, Wigan WN1 1YN
01942 489996 (89996) CURRENTLY NOT IN USE
www.wigan.gov.uk<http://www.wigan.gov.uk>
www.twitter.com/wigancouncil<http://www.twitter.com/wigancouncil>
www.facebook.com/WiganCouncilOnline<http://www.facebook.com/WiganCouncilOnline>




From: willLPD2I ***@***.***<mailto:***@***.***>>
Sent: 07 November 2022 09:20
To: data-to-insight/CIN-validator ***@***.***<mailto:***@***.***>>
Cc: Yates, Wendy ***@***.***<mailto:***@***.***>>; Author ***@***.***<mailto:***@***.***>>
Subject: Re: [data-to-insight/CIN-validator] Rule8897 (PR #173)

CAUTION External E-Mail: Take extra care before clicking links, attachments and actioning requests. Think Before you Click



@willLPD2I requested changes on this pull request.

________________________________

In cin_validator/rules/cin2022_23/rule_8897.py<https://clicktime.symantec.com/15t5ehGT3hZUREjD3dNgR?h=v_g-dQG7oCc3-vEzu4RN3hph9932MaAcE9Lb41cnUN0=&u=https://github.com/data-to-insight/CIN-validator/pull/173%23discussion_r1015176874>:

> + # Before you begin, rename the index so that the initial row positions can be kept intact.

+ df.index.name = "ROW_ID"

+

+ # lOGIC

+ # Implement rule logic as described by the Github issue.

+ # Put the description as a comment above the implementation as shown.

+

+ # Where present, if <AssessmentAuthorisationDate> (N00160) is on or after [Start_Of_Census_Year] then one or more <AssessmentFactors> (N00181) must be present within the same assessment module and must be a valid code

+ # Get collection period

+ header = data_container[Header]

+ ref_date_series = header[ReferenceDate]

+ collection_start, collection_end = make_census_period(ref_date_series)

+ condition1 = (df[AssessmentAuthorisationDate] >= collection_start) & (

+ df[AssessmentAuthorisationDate].notna()

+ )

+ condition2 = df[AssessmentFactors].isna()

Hi Wendy, this rule needs you to check both if AssessmentFactor is present AND if it's a valid code. The codes can be found here: https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1025195/Children_in_need_census_2022_to_2023_guide.pdf<https://clicktime.symantec.com/15t5Zs5Ab5st1HuHW4yXo?h=ACm0THubD-gADaF0SEf1mQqZRYrSIudb1PvrSlkQujM=&u=https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1025195/Children_in_need_census_2022_to_2023_guide.pdf<https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1025195/Children_in_need_census_2022_to_2023_guide.pdf%3chttps:/clicktime.symantec.com/15t5Zs5Ab5st1HuHW4yXo?h=ACm0THubD-gADaF0SEf1mQqZRYrSIudb1PvrSlkQujM=&u=https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1025195/Children_in_need_census_2022_to_2023_guide.pdf>>

To test if particular column on a particular row contains a valid code, I'd first make a list of valid codes, then use the .isin(codes_list_name) method on the column of the df, just as you have used .isna() and .notna() for conditions 1 and 2. If you feel you don't have time to do this, I'm happy to do it and send you an email with pictures explaining what I've done.

________________________________

In cin_validator/rules/cin2022_23/rule_8897.py<https://clicktime.symantec.com/15t5jXTjWKF4qBZ8bBmq3?h=oJAcSXJWdQngHY_JHLZ6ESPnTUfVqUGaMPoawjuXWTA=&u=https://github.com/data-to-insight/CIN-validator/pull/173%23discussion_r1015177605>:

> + df_issues["ERROR_ID"] = link_id

+ df_issues = df_issues.groupby("ERROR_ID")["ROW_ID"].apply(list).reset_index()

+ # Ensure that you do not change the ROW_ID, and ERROR_ID column names which are shown above. They are keywords in this project.

+ rule_context.push_type_1(

+ table=Assessments,

+ columns=[AssessmentAuthorisationDate, AssessmentFactors],

+ row_df=df_issues,

+ )

+

+

+def test_validate():

+ # Create some sample data such that some values pass the validation and some fail.

+ fake_data = pd.DataFrame(

+ [

+ {

+ "LAchildID": "child1",

As you need to check fro valid codes, you'll need to add some passing and failing codes here too!

________________________________

In cin_validator/rules/cin2022_23/rule_8897.py<https://clicktime.symantec.com/15t5pMf1xvvfF8P48kAyf?h=IU5pn1h1qDlsQkx5t4sskAYKJUADQpiJJfdgnM9oYZk=&u=https://github.com/data-to-insight/CIN-validator/pull/173%23discussion_r1015177861>:

> + # replace 2 with the number of failing points you expect from the sample data.

+ assert len(issue_rows) == 1

+ # check that the failing locations are contained in a DataFrame having the appropriate columns. These lines do not change.

+ assert isinstance(issue_rows, pd.DataFrame)

+ assert issue_rows.columns.to_list() == ["ERROR_ID", "ROW_ID"]

+

+ # Create the dataframe which you expect, based on the fake data you created. It should have two columns.

+ # - The first column is ERROR_ID which contains the unique combination that identifies each error instance, which you decided on earlier.

+ # - The second column in ROW_ID which contains a list of index positions that belong to each error instance.

+

+ # The ROW ID values represent the index positions where you expect the sample data to fail the validation check.

+ expected_df = pd.DataFrame(

+ [

+ {

+ "ERROR_ID": (

+ "child3",

This'll also need to account for the codes

—
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/15t5uBrJRYcFf5CygJa8H?h=uCEGKl8l-7v8uzTemm3KeDdRpbenYfzB8fgbIblci4A=&u=https://github.com/data-to-insight/CIN-validator/pull/173%23pullrequestreview-1170042517>, or unsubscribe<https://clicktime.symantec.com/15t5z23atAHr522uDryGu?h=t17mMUfT4dgcpPiMhW-osTZe07r31nkz_Igd3HaCmOk=&u=https://github.com/notifications/unsubscribe-auth/A3CF6DSGERTTJ6SEHB3QJULWHDCS5ANCNFSM6AAAAAARWHOE64>.
You are receiving this because you authored the thread.Message ID: ***@***.***<mailto:***@***.***>>

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________
>><<
[https://www.wigan.gov.uk/pub/emailsignature/footer.png]

______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________


—
Reply to this email directly, view it on GitHub<https://github.com/data-to-insight/CIN-validator/pull/173#issuecomment-1307411108>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AZ57426OUQ3ZVWIWXTCRE3LWHJXMDANCNFSM6AAAAAARWHOE64>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>
This message is intended for the use of the addressee only and may
contain confidential or privileged information. If you have received it in
error please notify the sender and destroy it. You may not use it or copy
it to anyone else.

E-mail is not a secure communications medium. Please be aware of this
when replying. All communications sent to or from the County Council 
may be subject to recording and/or monitoring in accordance  [...]

2022-11-09 09:47 UTC, willLPD2I approved these changes

2022-11-09 09:47 UTC, merged