Added4015
data-to-insight/CIN-validator pull request #184
Opened 2022-11-09 12:50 UTC by PhilDeakin

Added4015

2022-11-09 12:51 UTC, PhilDeakin commented on cin_validator/rules/cin2022_23/rule_4015.py
> +    df_cindet_issues.sort_values(["ROW_ID"], ignore_index=True, inplace=True)
This line matters... the " assert issue_rows.equals(expected_df) " near the bottom can fail otherwise.

2022-11-09 12:51 UTC, PhilDeakin commented on cin_validator/rules/cin2022_23/rule_4015.py
> +    df_cinplan_issues.sort_values(["ROW_ID"], ignore_index=True, inplace=True)
This line matters... the " assert issue_rows.equals(expected_df) " near the bottom can fail otherwise.

2022-11-14 14:28 UTC, willLPD2I requested changes
Some small changes needed. I am curious about the sort_values lines, I can see they're needed, I just wonder why when no other type_2 rule needs them to my knowledge, and I wonder if they'll have an effect down the road, or if we've got a bug somewhere that comes in before this rule is run that causes the issue.

2022-11-14 14:28 UTC, willLPD2I commented on cin_validator/rules/cin2022_23/rule_4015.py
> +    print(df_cindetail)
Try not to leave print statements in!

2022-11-14 14:28 UTC, willLPD2I commented on cin_validator/rules/cin2022_23/rule_4015.py
> +    df_cinplan = df_cinplan[["ROW_ID", "LAchildID", "CINdetailsID", "CINPlanStartDate"]]
I think lines 47-50 here are redundant?

2022-11-16 10:14 UTC, willLPD2I commented
@tab1tha just to check, we agreed that the sorting in all likelihood wasn't going to be a problem but we might see a) why it's needed and b) if we can do it in validate instead in case it messes with something unanticipated? So I might put this on hold?

2022-11-28 11:09 UTC, tab1tha commented
I have come back to this and haven't found a way to isolate the sort from the validate function while maintaining a logical prediction of what I expect the result to look like. 
This is because sorting is not needed on the data passed into the function (which the `test_validate()` functions has access to) but on the data generated within the validate function (which only the `validate() `function has access to)

2022-11-28 11:10 UTC, tab1tha approved these changes

2022-11-28 12:58 UTC, willLPD2I approved these changes

2022-11-28 13:34 UTC, tab1tha commented
Oops, I take that back.
I have just found a way to put it in the test_validate function. 
I'll push it since it is a small change @PhilDeakin

2022-11-28 13:37 UTC, tab1tha commented
I added this line `issue_rows.sort_values(["ROW_ID"], ignore_index=True, inplace=True)` just before this line `assert issue_rows.equals(expected_df)` and it worked. @PhilDeakin 

Merging this in...

2022-11-28 13:37 UTC, merged