Rule1103
data-to-insight/CIN-validator pull request #197
Opened 2022-11-15 12:44 UTC by GBurrel

Code completed

2022-11-16 11:36 UTC, willLPD2I requested changes
This looks good, we just need to make sure the merge has CINdetailsID too, so we don't accidentally merge referral dates &c from different CIN plan groups

2022-11-16 11:36 UTC, willLPD2I commented on cin_validator/rules/cin2022_23/rule_1103.py
> +                "AssessmentActualStartDate": "30/06/2021",  # Fails as referral date is after assessment start
You'll need to add CINdetailsIDs to these sample tables too

2022-11-16 11:36 UTC, willLPD2I commented on cin_validator/rules/cin2022_23/rule_1103.py
> +                "ROW_ID": [3],
And CIndetailsIDs to these, please

2022-11-16 12:14 UTC, GBurrel commented
Hi @willLPD2I - I've made the necessary changes to the code. Hopefully it's come through for your review.

2022-11-17 15:10 UTC, willLPD2I approved these changes

2022-11-21 13:51 UTC, merged