Rule 8670Q
data-to-insight/CIN-validator pull request #203
Opened 2022-11-22 11:36 UTC by phoebefryer

2022-11-22 13:30 UTC, phoebefryer commented
@willLPD2I yes, I feel like there should be a better way than I've done but my quick search for an existing function didn't yield anything, but it definitely wasn't the most thorough of googles. I'd be interested in knowing what can do it, or a more efficient loop, I'm sure it could be cut down a little bit

2022-11-22 14:32 UTC, tab1tha commented
Found something !

You can replace that loop with this line
`latest_date = collection_end - pd.tseries.offsets.BDay(45)`

BDay makes sure that it only considers business days. It is pandas' business day date offset. @phoebefryer @willLPD2I 

https://stackoverflow.com/questions/44288465/pandas-to-timedelta-with-business-days

2022-11-25 09:41 UTC, willLPD2I commented
@phoebefryer , I might be having a silly moment here, but the rule says 'Assessment started more than 45 working days before the end of the census year' and you're failing rows that are within 45 days of the end of the census year, so, less than 45 days before the end of the census year? I think it's checking that assessments don't go longer then 45 working days? I've spent so long reading and re reading the rule though that I think I'm confusing myself and I might have to come to it with fresh eyes.

2022-11-25 10:31 UTC, phoebefryer commented
@willLPD2I I think you're right, I think I must have got myself in a bit of a twist with that one with the phrasing. I've now amended it so it should now be right

2022-11-25 11:39 UTC, willLPD2I commented
> @willLPD2I I think you're right, I think I must have got myself in a bit of a twist with that one with the phrasing. I've now amended it so it should now be right

Okay! I know when I look at something too long it loses meaning and I spent so long looking at this this morning that I couldn't remember what means what!

2022-11-25 11:46 UTC, willLPD2I requested changes

2022-11-25 11:46 UTC, willLPD2I commented on cin_validator/rules/cin2022_23/rule_8670Q.py
> +            df_issues[AssessmentAuthorisationDate], df_issues[AssessmentActualStartDate]
Okay, so if the code checks that assessment authorisation data .isna(), then this makes the first part of this link ID a NaN, so LAchildID might be better!

2022-11-25 11:46 UTC, willLPD2I commented on cin_validator/rules/cin2022_23/rule_8670Q.py
> +                # Fail, start date is withing 45wd of reference date
Can you update these comments to reflect the rule change please?

2022-11-30 12:07 UTC, tab1tha commented
> > @willLPD2I I think you're right, I think I must have got myself in a bit of a twist with that one with the phrasing. I've now amended it so it should now be right
> 
> Okay! I know when I look at something too long it loses meaning and I spent so long looking at this this morning that I couldn't remember what means what!

same

2022-11-30 12:20 UTC, tab1tha commented
@phoebefryer 
Side note: For finishing touches like this, if you prefer that Will and I wrap it up, we'll be happy to do that too.

2022-12-08 11:04 UTC, merged

2023-03-15 15:54 UTC, tab1tha commented on cin_validator/rules/cin2022_23/rule_8670Q.py
> +    print(issue_rows)
I'll do a pull request to remove these.