Rule 4009 : CIN Plan cannot end after the child’s Date of Death
data-to-insight/CIN-validator pull request #213
Opened 2022-11-28 17:04 UTC by bellt101

Fixes #78

2022-11-29 09:12 UTC, willLPD2I commented
I've updated this with main because otherwise the code that makes type 2 rules work isn't there

2022-11-29 09:22 UTC, willLPD2I requested changes

2022-11-29 09:22 UTC, willLPD2I commented on cin_validator/rules/cin2022_23/rule_4009.py
> +                "ROW_ID": [6],
Hi Tracy, you've used CINplanEndDates in this expected df ERROR_ID, but in your validate function, you've set the ERROR_ID to put out PersonDeathDate, so, you'll need to either update these to reflect that, or update the statement that makes the ERROR_ID in validate to reflect these.

2022-12-08 11:08 UTC, tab1tha commented
Hi @bellt101 will you prefer if Will and I complete this so that you can move on to newer rules?.
We are happy either way.

2022-12-22 14:21 UTC, tab1tha commented
Hi @bellt101, 

The review will be continued here https://github.com/data-to-insight/CIN-validator/pull/266/files so I'll close this one.

2022-12-22 14:21 UTC, closed without merging